version: '3.1'

services:
  zoo1:
    image: zhicwu/zookeeper:3.5
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZK_MY_ID: 1
      ZK_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
    image: zhicwu/zookeeper:3.5
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZK_MY_ID: 2
      ZK_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
    image: zhicwu/zookeeper:3.5
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZK_MY_ID: 3
      ZK_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888